### ISSUE TITLE
Doesnt work, no proper instructions

### ISSUE THREAD

**Issue by VinylNerd** [cholonam/Sinetek-rtsx#15]
can't seem to find proper instructions on how to use this successfullly anywhere, multiple people suggest placing in multiple places but no explanation on here https://github.com/cholonam/Sinetek-rtsx

i have placed in L/E with no luck, on T440P with RTS5227 card which should be working 

please make proper instructions how to get this working :)

**Comment by cholonam** [comment]
There are multiple ways to get this kext working, just as any other kext. The right location will depend on your particular boot loader (there many guides out there). I have not personally tried L/E, but that should work too, for any boot loader (unless you have SIP enabled, which might prevent it from loading).

The only chip I can test/support is the one I have (RTS525A). RTS5227 may just not work, or work with many glitches, since it has not been tested. I encourage you (or anyone with this or other similar chip) to further develop the kext and submit a pull request.

**Comment by VinylNerd** [comment]
thanks for the reply, im not really sure how i would further develop this because this seems to be the hardest documentation for me to understand

there isnt really a guide how to use the compile-time options or boot options or clafification if they work with clover, im not comfortable just putting random commands into random places on my computer and althought i understand this guide is only for your card id still be confused following your instructions

like for example you say its only for your card, you say to use this command only if you have the same card "-rtsx_mimic_linux" but dont explain at all where the command should be entered?

**Comment by VinylNerd** [comment]
my card has been listed as working by numerous people but no one responds or explains how they got it to work, im assuming they edited the kext or did more than just place the kext in one place and update there permissions and rebuild the kernel cache, seems to me something is missing in the guide, maybe its something really simple i dont understand, but its not clear to me how to get this to work based on any instructions, i just need help troubleshooting it cause i dont understand whats happening.
