### ISSUE TITLE
Support for RTS5260 PCI Card Reader

### ISSUE THREAD

**Issue by wu-hongjun** [cholonam/Sinetek-rtsx#17]
Hi, I have a razer blade adv 10th gen with a RTS5260 card reader, and ID is `0x526010EC` I am using the newest 2.3 version, and out of the box it did not work. Then I went into the kext and saw `IOPCIMatch` and it did not match my device ID. Then I added my device ID `0x526010EC` I found the driver in PCI device is loaded, but the card still cannot be detected. I wonder if anyone has any idea or I need to make some other changes else than IOPCIMatch? I am also willing to test new versions of this kext. Thanks!

![image](https://user-images.githubusercontent.com/27667864/99496788-c32f7f80-2929-11eb-8a0c-754c9f55a25b.png)
![image](https://user-images.githubusercontent.com/27667864/99497079-39cc7d00-292a-11eb-9b9c-f1a444d54c45.png)

**Comment by cholonam** [comment]
Hi, I'm afraid any chip other than RTS525A has very low chances or working using this kext without any modifications. You can try using the different boot flags (with/without `-rtsx_mimic_linux`, with `-rtsx_no_adma`, with `rtsx_timeout_shift=2`), but I can't assure you anything. (Let me know if you get any success, and I'll update the README)

At least I can see that your chip [is supported in Linux](https://elixir.bootlin.com/linux/latest/source/drivers/misc/cardreader/rts5260.c), so adding support won't be too difficult if you know how to code.

I have no plans to add support for chips other than mine (RTS525A) in the near future, basically because it's almost impossible since I cannot test a chip a don't have. Some day I may just port the whole Linux driver which would give support for all this family of chips, but currently I have zero free time, so that will have to wait at least a few years (I hope I still have the same laptop or at least an RTS-family card reader by then...).
