### ISSUE TITLE
can not get kext to work

### ISSUE THREAD

**Issue by VinylNerd** [cholonam/Sinetek-rtsx#22]
i can not get this to pickup or read any SD card whatsoever, but it looks like its loading, quite confused. Big Sur 11.2.1 on T440P with OpenCore 0.6.6

![Screen Shot 2021-02-14 at 5 57 07 PM](https://user-images.githubusercontent.com/72950020/107884660-134cbc80-6eee-11eb-8c24-58d677c94fb9.png)
![Screen Shot 2021-02-14 at 5 56 49 PM](https://user-images.githubusercontent.com/72950020/107884661-147de980-6eee-11eb-8a05-93b17a438320.png)

**Comment by cholonam** [comment]
The kext is definitely loading. RTS5227 has been reported to work, at least on some hardware (see PR #18). This is what I would try:

0. Make sure the computer does not sleep during testing and always do hard resets (turn off, then on), not just a warm reboot.
1. Start by using the most conservative flags: `-rtsx_no_adma -rtsx_ro rtsx_timeout_shift=2`
2. If that does not work, try adding the mimic_linux flag: `-rtsx_mimic_linux -rtsx_no_adma -rtsx_ro rtsx_timeout_shift=2`
3. If still no luck, try with ADMA, no mimic_linux: `-rtsx_ro rtsx_timeout_shift=2`
4. And with mimic_linux: `-rtsx_mimic_linux -rtsx_ro rtsx_timeout_shift=2`

If with any of these you get to see the drive on the desktop, next would be to remove parameters until you get the minimum set that make the kext work (and letting me know what worked so that I can update the README). The last parameter you should remove is `-rtsx_ro`,  which will allow mounting the card on read-write mode.

On a side note, I think @Sniki is about to test on a T440S (maybe similar to your hardware, see [here](https://github.com/cholonam/Sinetek-rtsx/pull/18#issuecomment-775499372)).

All that said, these chips are very picky, the same chip on a different hardware, or with a different card may show different results.. good luck :)

**Comment by VinylNerd** [comment]
thanks so much for your reply!

i tried all 4 of these combos and unfortunately none work :(

i did hard reset and cleared nvram each time to make sure the correct bootargs were applied, i also tried with multiple cards to be sure

**Comment by CLAY-BIOS** [comment]
> 非常感谢你的回复！
> 
> 我尝试了所有4种连击，但不幸的是没有任何工作:(
> 
> 我每次都进行硬重置并清除nvram以确保应用了正确的bootargs，我还尝试了多张卡以确保

SD卡在win10中能否正常工作？

**Comment by VinylNerd** [comment]
> > 非常感谢你的回复！
> > 我尝试了所有4种连击，但不幸的是没有任何工作:(
> > 我每次都进行硬重置并清除nvram以确保应用了正确的bootargs，我还尝试了多张卡以确保
> 
> SD卡在win10中能否正常工作？

sorry, i dont have windows 10, MacOS is my only operating system as i only have a single 480GB SSD. however im fairly positive it would work.

**Comment by Sniki** [comment]
> The kext is definitely loading. RTS5227 has been reported to work, at least on some hardware (see PR #18). This is what I would try:
> 
> 1. Make sure the computer does not sleep during testing and always do hard resets (turn off, then on), not just a warm reboot.
> 2. Start by using the most conservative flags: `-rtsx_no_adma -rtsx_ro rtsx_timeout_shift=2`
> 3. If that does not work, try adding the mimic_linux flag: `-rtsx_mimic_linux -rtsx_no_adma -rtsx_ro rtsx_timeout_shift=2`
> 4. If still no luck, try with ADMA, no mimic_linux: `-rtsx_ro rtsx_timeout_shift=2`
> 5. And with mimic_linux: `-rtsx_mimic_linux -rtsx_ro rtsx_timeout_shift=2`
> 
> If with any of these you get to see the drive on the desktop, next would be to remove parameters until you get the minimum set that make the kext work (and letting me know what worked so that I can update the README). The last parameter you should remove is `-rtsx_ro`, which will allow mounting the card on read-write mode.
> 
> On a side note, I think @Sniki is about to test on a T440S (maybe similar to your hardware, see [here](https://github.com/cholonam/Sinetek-rtsx/pull/18#issuecomment-775499372)).
> 
> All that said, these chips are very picky, the same chip on a different hardware, or with a different card may show different results.. good luck :)

This chip is confirmed from my guides on tonymacx86 and my laptops to be working fine on Lenovo ThinkPads T440P, T440S, T440, L440, X240

Haven't tested lower IOSleep value yet but in general it’s perfectly fine now.

**Comment by VinylNerd** [comment]
> > The kext is definitely loading. RTS5227 has been reported to work, at least on some hardware (see PR #18). This is what I would try:
> > 
> > 1. Make sure the computer does not sleep during testing and always do hard resets (turn off, then on), not just a warm reboot.
> > 2. Start by using the most conservative flags: `-rtsx_no_adma -rtsx_ro rtsx_timeout_shift=2`
> > 3. If that does not work, try adding the mimic_linux flag: `-rtsx_mimic_linux -rtsx_no_adma -rtsx_ro rtsx_timeout_shift=2`
> > 4. If still no luck, try with ADMA, no mimic_linux: `-rtsx_ro rtsx_timeout_shift=2`
> > 5. And with mimic_linux: `-rtsx_mimic_linux -rtsx_ro rtsx_timeout_shift=2`
> > 
> > If with any of these you get to see the drive on the desktop, next would be to remove parameters until you get the minimum set that make the kext work (and letting me know what worked so that I can update the README). The last parameter you should remove is `-rtsx_ro`, which will allow mounting the card on read-write mode.
> > On a side note, I think @Sniki is about to test on a T440S (maybe similar to your hardware, see [here](https://github.com/cholonam/Sinetek-rtsx/pull/18#issuecomment-775499372)).
> > All that said, these chips are very picky, the same chip on a different hardware, or with a different card may show different results.. good luck :)
> 
> This chip is confirmed from my guides on tonymacx86 and my laptops to be working fine on Lenovo ThinkPads T440P, T440S, T440, L440, X240
> 
> Haven't tested lower IOSleep value yet but in general it’s perfectly fine now.

Hey Snicki, thanks for the reply, and thanks for all your hard work on thinkpad series.

I've taken a look at your EFI and config to see if there is anything i can figure out, i noticed you are using the -rtsx_mimic_linux boot arg and that you said it was working, do you actually have a T440P personally to test it on, if you have an EFI for me to try i will pop it on a USB and add my serials and try to boot, or if you have any suggestion, im very keen to fix this so that we can be confident it works for all T440P's with RTS5227

add me on discord if you'd like, Querkle#1589
