### ISSUE TITLE
HP Probook 450 g3

### ISSUE THREAD

**Issue by Leo3213** [cholonam/Sinetek-rtsx#29]
high cpu usage an startup?

**Comment by Leo3213** [comment]
os thought it was still mounted when it was not in computer

**Comment by Leo3213** [comment]
I appeciate everything you have done with this driver :)

**Comment by Leo3213** [comment]
keeps tryning to load sd card when i put it back in a second time

pug in, take out, plug in

**Comment by cholonam** [comment]
What is your chip number? Did you check the logs? Did you try the different boot arguments?

I cannot help you with this little info.

**Comment by Leo3213** [comment]
hey sorry Im late to respond

Im kind of a noob in this regard.

Would you mind walking me through the process if thats ok.

That way not only it will work for me but others as well :)

**Comment by Leo3213** [comment]
[pcidevices.txt](https://github.com/cholonam/Sinetek-rtsx/files/6523480/pcidevices.txt)

**Comment by Leo3213** [comment]
is that information helpful?

**Comment by Leo3213** [comment]
Ok i added the bootflag and it didnt freeze this time however if i take it out and put it back in it doesnt detect it.

also it adds some time to the boot

and its killing my batterylife

**Comment by cholonam** [comment]
I can see from the pcidevices.txt that your chip is RTS522A. Only RTS525A is supported by this kext, but RTS522A has been reported to work by some user, as you can see in the README file's "Chips known to work" section:

> Adding boot parameter `rtsx_sleep_wake_delay_ms=1000` makes it work with sleep enabled. (See issue #27)

This user did not mention any of the issues you are having, but since every hardware is different, it could be that you are just out of luck with this kext.

I would try with other boot arguments as well: Keep `rtsx_sleep_wake_delay_ms=1000`, try with/without `-rtsx_mimic_linux`, with/without `-rtsx_no_adma`, etc. all combinations, basically, until you find what works best with your hardware (it's just a matter of trial and error, sadly).

Good luck, and please report back with your findings so that I can update the README file.

**Comment by Leo3213** [comment]
will Do I just wanted to be able to help others :)
