### ISSUE TITLE
Newer implmentation based on linux

### ISSUE THREAD

**Issue by Charlyo** [cholonam/Sinetek-rtsx#33]
Dear @cholonam:

It appears someone has already integrated the linux drivers into a kext: 

https://github.com/0xFireWolf/RealtekCardReader

Might be worth a taking a look.

**Comment by cholonam** [comment]
I will not have time to test this kext for the time being, but it looks like somebody finally took the time/commitment that it takes to get these chips working on macOS. Way to go @0xFireWolf !

**Comment by Charlyo** [comment]
@simprecicchiani

**Comment by cholonam** [comment]
A quick test of @0xFireWolf's kext on my system shows no issues and a very good performance. After I can do a more thorough test, my plan is to archive this repository and redirect this kext's users to [RealtekCardReader](https://github.com/0xFireWolf/RealtekCardReader), since it seems like the way forward for users of these card readers.

@Charlyo Thank you for letting me know about this project.

**Comment by Charlyo** [comment]
Thanks to you @cholonam for all your time an effort put into this project. I'll always appreciate that.
